### ISSUE TITLE
Actividad 4 - infografia 

### ISSUE THREAD

**Issue by ErikCuevas03** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ErikCuevas03#1]
[actividad 4 - infografia - Erik - Cuevas .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-ErikCuevas03/files/14609552/actividad.4.-.infografia.-.Erik.-.Cuevas.pdf)

**Comment by SandyMarissaGs** [comment]
De acuerdo a la rúbrica obtuviste un porcentaje de 19%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
